dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - software-terms
  - networking-terms
  - makefile
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
enabled: true
useGitignore: true
ignorePaths:
  - .config/requirements*
  - \.*
  - cspell.config.yaml
  - mkdocs.yml
  - pyproject.toml
  - tox.ini
  - selenium/Containerfile
  - selenium/init.go

languageSettings:
  - languageId: python
    allowCompoundWords: false
